name: Visit App Every 4 Hours

on:
  schedule:
    # Runs every 4 hours (e.g., 00:00, 04:00, 08:00, etc. in UTC)
    - cron: "0 */4 * * *"

jobs:
  visit_app:
    runs-on: ubuntu-latest
    steps:
      - name: Visit Application Endpoint
        run: |
          curl -I https://thai-restuarants-analysis.streamlit.app